version: '2'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: cubeearth/headless-desktop:ubuntu_bionec
    environment:
      - STARTUP=xclock
    volumes:
    - $HOME/.containers/xpra/sockets:/var/run/xpra:rw
